### ISSUE TITLE
Blog with embedded CMS?

### ISSUE THREAD

**Issue by moracoderz** [bradgarropy/ama#10]
Hello Brad! 👋🏼

Could you tell me how you integrate your blog with embedded CMS?

I'm starting as a frontend with React and leaving the WordPress environment to do new things, so I wonder how can I do something like that without WP. Little lost and overwhelmed with too many new things I'm learning right now.

Or is ok use WordPress as a backend or do you have a better suggestion for a CMS or e-commerce?

Thanks in advance!

**Comment by bradgarropy** [comment]
My best suggestion for an embedded CMS would be [Gatsby](https://www.gatsbyjs.com)! They have some [great documentation](https://www.gatsbyjs.com/docs/how-to) that walks you through how to create a blog from `markdown` files.

But if you're just looking to get up and running, they also offer _starters_, like the official [gatsby-starter-blog](https://www.gatsbyjs.com/starters/gatsbyjs/gatsby-starter-blog).
