### ISSUE TITLE
Svelte, Netlify, and Fauna

### ISSUE THREAD

**Issue by billpliske** [bradgarropy/ama#11]
Hi Brad,

Cool video!  A current React guy here, loving Svelte and Sveltekit, so far.
Svelte beginners (like myself) had some setup gaps in this video, and was hoping one of you could clarify (or point me in the right direction)

Mainly discussing the integration between Svelte (or Sveltekit), Netlify, and Fauna.

Successes!
------------------
- Uploaded my GraphQL schema to Fauna (too cool).
- Queried and mutated a few things in Fauna playground (easy!)

Questions
-----------------
- How to connect my Svelte (or Sveltekit) app to Fauna. In React, it's a uri. But I'm not locating this uri endpoint (You said they're the same for everyone?).
- Or, is there a way we should be connecting to Fauna via Netlify (or the netlify-cli)?

The end goal here is a simple Sveltekit app I run on Netlify, using serverless to connect to Fauna to pull in data. (first part easy, second part less so)

Since I'm not specific finding videos on this ... my assumption is that it must be easy, and I'm making this too hard!  

Any tips appreciated, man.

**Comment by bradgarropy** [comment]
Hey @billpliske,
I know we spoke a bit a while ago, but did you resolve this issue? Let me know what help you still need!

**Comment by billpliske** [comment]
Hey man, thanks for getting back.

I did eventually find a solid approach with Svelte, Fauna, and Netlify, using GraphQL.
**_In a nutshell, I did this:_**

1. Made a repo with a starter Svelte template, and connected it to Netlify.
2. Locally, used the Netlify CLI to do a `netlify init`, and also a 'netlify functions:create`, choosing the `fauna-graphql` option.
3. Create my DB in Fauna, filled out my schema locally (in side functions/fauna-graphql/), and then importing that schema into Fauna.
4. Creating a new server key, and copy/pasting that secret code as my ENV var locally, and in my Netlify admin screen for the repo. Now everything is connected.

Those were the big steps, I suppose. I have to admit, it's quite nice to only have to worry about making the GraphQL calls in the front end, with Fauna and the Netlify serverless function taking care of the backend.

And no more Digital Ocean account needed.!

**Comment by bradgarropy** [comment]
That sounds like exactly the approach I would have taken, nice job!

I'm still personally trying to figure out the different between the following:

- Collection of single use Netlify Functions
- `express` running in a Netlify Function
- `graphql` running in a Netlify Function

I know there are performance and size limitations in Netlify Functions, but I'm not sure what the recommended architecture is for a backend based totally on serverless functions.
