### ISSUE TITLE
If you got a job offer from California, would you consider moving?

### ISSUE THREAD

**Issue by silui** [bradgarropy/ama#2]

**Comment by bradgarropy** [comment]
## ✅ ANSWER
_[live on stream][answer]_

After interviewing on site with [Facebook][facebook] in [Palo Alto, California][map] I don't think I'd ever move there.

While I love the thought of being close to both the beach and the mountains, California's cost of living is much higher than Texas. Both my family and my wife's family are here in Texas, and it's great to have them around as our children grow up. I also love the Texas culture.

Everyone is nice and friendly, and we are very proud of our state. The Texas country music scene is also a part of who I am, and it just doesn't exist in California. I even created [Daily Texas Country][dtxc] to grow a community around concerts, music, and dancing.

And finally, Austin is really growing as a tech hub in the United States. We've got plenty of big and small companies to choose from, and more are moving here every year. So I don't think the developer job market will saturate anytime soon.

[answer]: https://www.twitch.tv/videos/713663883
[facebook]: https://www.facebook.com/careers
[map]: https://www.google.com/maps/place/Facebook/@37.485073,-122.1504711,17z/data=!4m5!3m4!1s0x808fbc96de8dc419:0x64979e438bf4e3a5!8m2!3d37.485073!4d-122.1482824
[dtxc]: https://dailytexascountry.com
