### ISSUE TITLE
How did you go from a devops engineer to a frontend engineer?

### ISSUE THREAD

**Issue by sleepyArpan** [bradgarropy/ama#3]

**Comment by sleepyArpan** [comment]
Closing this now. Was answered [here](http://www.twitch.tv/bradgarropy/v/706675221?sr=a&t=2661s) at around 44:19. :)

**Comment by bradgarropy** [comment]
## ✅ ANSWER
_[live on stream][answer]_

### 🔙 background

I was working at [Dell][dell] as a devops engineer for about seven years. I was writing Python scripts, creating Jenkins jobs, and monitoring hardware. I had stagnated at Dell, I wasn't learning anything new and my opportunity for another promotion was running dry. So I began learning web development.

### 🧠 learning process

I taught myself for free using nothing but documentation, blog posts, YouTube videos, and developer communities. I studied for about two hours each night while still working full time at Dell. Over the course of about two years I taught myself what I needed to know to begin applying.

### 👔 applications and interviews

The application process took about six months. I used [LinkedIn][linkedin] as my primary job search platform. I applied to something like 50 jobs and went on around 10 interviews. I interviewed with companies like [Facebook][facebook], [VRBO][vrbo], [Snap Kitchen][snapkitchen], and [Adobe][adobe]. I got a few offers, a few rejections, and plenty of radio silence.

### 🏆 jackpot

Ultimately I accepted an offer from [Adobe][adobe] and it's literally the best thing I've ever done. I increased my salary by 40%, gained some really great co-workers, and get to work in a really cool office with all the latest web technology.

### ✨ lessons learned

I learned a ton throughout this process, but I'll try and summarize with some bullet points.

- Update your resume and go on an interview at least once a year.
- Define what you are looking for in a job and don't compromise.
- Establish credibility with side projects.
- Leverage social media to meet other developers.
- Don't let a bad interview or a rejection get you down.

[answer]: https://www.twitch.tv/videos/713663884
[dell]: https://www.delltechnologies.com/en-us/index.htm
[linkedin]: https://www.linkedin.com/in/bradgarropy
[facebook]: https://www.facebook.com/careers
[vrbo]: https://lifeatexpediagroup.com/brands
[snapkitchen]: https://www.snapkitchen.com/careers
[adobe]: https://www.adobe.com/careers.html
