### ISSUE TITLE
Do you have any freelancing experience?

### ISSUE THREAD

**Issue by csellis** [bradgarropy/ama#4]

**Comment by bradgarropy** [comment]
## ✅ ANSWER
_[live on stream][answer]_

Yes, I built [Iron Jimmy][ironjimmy] very early on in my web development learning process for a friend for $300. It's a [Gatsby][gatsby] and [Shopify][shopify] e-commerce store for barbell sleeves.

The most difficult aspect of freelancing was getting the client to provider me assets/content. Product photos, product descriptions, about page content, a logo, a design, literally anything.

As soon as I finished the website, I wrote up a [freelancing contract][contract] in my own words about what I expect from a client before development can start, and how the contract can be terminated if these deliverables are not met.

Based on my one and only freelancing experience I would do it again.

[contract]: https://docs.google.com/document/d/1YRZvrwKP7HPCU_Oqf6GcFwiONFGXJX5UZ3nxPlS-WsQ/edit?usp=sharing
[gatsby]: https://www.gatsbyjs.org
[shopify]: https://www.shopify.com
[ironjimmy]: https://ironjimmy.com
[answer]: https://www.twitch.tv/videos/714707020
[next]: https://nextjs.org
