### ISSUE TITLE
Have you worked with Next.js? If so, how do you like it?

### ISSUE THREAD

**Issue by colabottles** [bradgarropy/ama#6]
Have you worked with NextJS yet? And if so, How do you like it?

**Comment by bradgarropy** [comment]
## ✅ ANSWER
_[live on stream][answer]_

Yes! The last time I used [Next.js][next] was back in v6. I really enjoyed it! Next has all the features you would expect: zero config build process, file system routing, SSG and SSR capabilities, API routes, [TypeScript][typescript] support, hot module reloading, etc.

If I'm building anything except a truly static site, I'd use Next.js. Especially with the way [Gatsby][gatsby] is going.

[typescript]: https://www.typescriptlang.org
[gatsby]: https://www.gatsbyjs.org
[answer]: https://www.twitch.tv/videos/714707019
[next]: https://nextjs.org
