### ISSUE TITLE
What’s a day in the life at Adobe look like?

### ISSUE THREAD

**Issue by bmorrisondev** [bradgarropy/ama#7]
Been a user of Adobe products since CS1 (I think). Ive always wondered what it’d be like to work there. Thanks!

**Comment by bradgarropy** [comment]
## ✅ ANSWER
_[live on stream][answer]_

### ☕ morning routine

I generally start my day between 8:30AM and 9AM. We follow the Kanban methodology at [Adobe][adobe], so I sit down and either keep working on my task in progress, or pull one from the _Ready To Do_ column.

### 🤝🏼 collaboration

We use [GitHub][github] for source control so I spend a lot of time there doing code reviews for the other frontend developer on my team. There's a lot of healthy discussion going on there!

### 📅 meetings

We use [Outlook][outlook] and [Slack][slack] for communication. We run a 15 minute standup every day, backlog grooming on Monday, and demo on Friday. Other than that my calendar remains pretty empty.

### 💻 projects

My team works on greenfield e-commerce SaaS products. I get to use all the fun frontend technologies like React, GraphQL, jest, storybook, react-testing-library, and styled-components. We use [Jenkins][jenkins] for continuous integration and have all of our integration and deployments automated through pipelines.

[jenkins]: https://www.jenkins.io
[slack]: https://slack.com
[outlook]: https://outlook.live.com/owa
[github]: https://github.com/adobe
[answer]: https://www.twitch.tv/videos/714707018
[next]: https://nextjs.org
[adobe]: https://www.adobe.com
