### ISSUE TITLE
Where is a good place for someone to start learning about programming?

### ISSUE THREAD

**Issue by Juancastmi** [bradgarropy/ama#9]
Where is a good place for someone to start learning about programming but doesn't really know much about computers?

**Comment by bradgarropy** [comment]
## ✅ ANSWER
_[live on stream][answer] (bad audio quality)_

### 🏀 fundamentals

To begin learning programming, you do need basic familiarity with how to operate a computer. Installing and opening applications, decent typing skills, and knowledge of the file system.

### 🗺 roadmap

Once you've crossed those hurdles, web development has a fairly low barrier to entry. I would start by learning `html` to get things to show up on a web page. Then move on to `css` to make those things look nicer. And finally dive into the vast world of `javascript`, which brings interactivity to your websites.

### 📺 youtube

You can learn everything you need to know online. I would recommend starting with [YouTube](https://youtube.com), there are lots of free tutorials you can check out.

Here are a few content creators that helped me out when I first started learning web development.

- [The Net Ninja](https://www.youtube.com/c/TheNetNinja)
- [Traversy Media](https://www.youtube.com/c/TraversyMedia)
- [Level Up Tutorials](https://www.youtube.com/c/LevelUpTuts)

_Good luck, you can always come ask me questions!_

[answer]: https://www.twitch.tv/videos/742516530
